version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 25
  ignore:
  - dependency-name: ajv
    versions:
    - 7.0.4
    - 7.1.0
    - 7.1.1
    - 7.2.1
    - 7.2.3
    - 7.2.4
    - 8.0.1
    - 8.0.2
    - 8.0.3
    - 8.0.5
    - 8.1.0
  - dependency-name: rollup
    versions:
    - 2.38.3
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.43.1
    - 2.45.0
    - 2.45.1
    - 2.45.2
  - dependency-name: ts-loader
    versions:
    - 8.0.15
    - 8.0.18
    - 8.1.0
    - 9.0.0
    - 9.1.0
  - dependency-name: "@wessberg/rollup-plugin-ts"
    versions:
    - 1.3.10
    - 1.3.11
  - dependency-name: "@microsoft/api-documenter"
    versions:
    - 7.12.11
    - 7.12.12
    - 7.12.13
    - 7.12.14
    - 7.12.15
    - 7.12.16
    - 7.12.17
    - 7.12.19
    - 7.12.20
    - 7.12.21
    - 7.12.22
    - 7.12.6
    - 7.12.8
    - 7.12.9
    - 7.13.0
    - 7.13.1
  - dependency-name: typedoc
    versions:
    - 0.20.23
    - 0.20.24
    - 0.20.25
    - 0.20.27
    - 0.20.28
    - 0.20.29
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: "@textile/grpc-powergate-client"
    versions:
    - 2.0.0
    - 2.1.0
    - 2.2.0
    - 2.3.1
    - 2.3.2
    - 2.3.3
  - dependency-name: libp2p-crypto
    versions:
    - 0.19.1
    - 0.19.2
    - 0.19.3
  - dependency-name: multibase
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: "@microsoft/api-extractor"
    versions:
    - 7.13.2
    - 7.13.3
    - 7.13.4
    - 7.13.5
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.3.1
    - 4.3.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: "@types/chai"
    versions:
    - 4.2.16
  - dependency-name: "@types/ws"
    versions:
    - 7.4.1
