name: Auto-approve
on:
  pull_request:
    branches:
      - master

jobs:
  auto-approve:
    name: Auto-approve
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - uses: reviewdog/action-misspell@v1
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: ${{ secrets.github_token }}
